PKX-464 Added contactus model for contact us form
PakistanX/edx-platform pull request #125
Opened 2021-09-16 08:50 UTC by mubtadaali

### [PKX-464](https://edlyio.atlassian.net/browse/PKX-464) Added contactus model for contact us form

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2021-09-16 10:08 UTC, emzubair requested changes

2021-09-16 10:09 UTC, emzubair commented on openedx/features/pakx/lms/overrides/models.py
> +    phone = models.CharField(max_length=16)
@mubtadaali `pylint` & `isort` issues are related to our custom development so I think we can resolve these.

2021-09-16 11:53 UTC, emzubair submitted a review, later dismissed
👍🏽

2021-09-17 09:14 UTC, emzubair approved these changes
👍🏽

2021-09-17 09:35 UTC, muhammadqaisar74 approved these changes

2021-09-17 09:41 UTC, merged