PKX-246 Added user course enrollments API - WIP
PakistanX/edx-platform pull request #61
Opened 2021-06-15 06:32 UTC by mubtadaali

### [PKX-246](https://edlyio.atlassian.net/browse/PKX-246) Added user course enrollments API

2021-06-15 10:51 UTC, emzubair requested changes
Can we add docstrings for classes and methods as it is necessary for `pylint`

2021-06-15 11:12 UTC, tasawernawaz commented
> Can we add docstrings for classes and methods as it is necessary for `pylint`

![maza](https://user-images.githubusercontent.com/4245618/122043091-624f2380-cdf4-11eb-9720-16317be2647d.gif)

2021-06-21 11:25 UTC, emzubair approved these changes
👍🏽

2021-06-21 11:25 UTC, emzubair commented on openedx/features/pakx/lms/pakx_admin_app/serializers.py
> +    def get_grades(obj):
are we using this method?

2021-06-21 11:38 UTC, mubtadaali commented on openedx/features/pakx/lms/pakx_admin_app/serializers.py
> +    def get_grades(obj):
yes, we are

2021-06-21 11:40 UTC, merged