PKX-248 User Course Enrolment - WIP
PakistanX/edx-platform pull request #74
Opened 2021-06-24 08:50 UTC by Faizan-at-Edly

[PKX-248](https://edlyio.atlassian.net/browse/PKX-248) User course enrolment

2021-06-24 10:24 UTC, emzubair requested changes

2021-06-24 10:24 UTC, emzubair commented on common/djangoapps/student/models.py
> -import inspect
revert this change.

2021-06-24 10:24 UTC, emzubair commented on openedx/features/pakx/lms/pakx_admin_app/views.py
> +        import pdb
remove this line

2021-06-24 10:24 UTC, emzubair commented on openedx/features/pakx/lms/pakx_admin_app/views.py
> +from django.db.models import F, Prefetch
`Q` is being used in some classes, please import that

2021-06-24 10:25 UTC, emzubair commented
@Faizan-at-Edly run isort in the lms shell to resolve isort issues 
i.e in lms shell `isort common/djangoapps/student/models.py`

2021-06-28 12:04 UTC, emzubair commented on openedx/features/pakx/lms/pakx_admin_app/tasks.py
> +                for course_key in course_keys:
reverse the orders of these loops, so that `course_key = CourseKey.from_string(course_key)` can be called equal to the number of users.

2021-06-28 12:05 UTC, emzubair commented on openedx/features/pakx/lms/pakx_admin_app/tasks.py
> +def send_course_enrolment_email(users, course_keys):
this should be a `celery` task as well.

2021-06-28 20:56 UTC, mubtadaali commented on openedx/features/pakx/lms/overrides/urls.py
> +            course_id=settings.COURSE_ID_PATTERN),
why we are breaking this line?

2021-06-28 20:56 UTC, mubtadaali commented on openedx/features/pakx/lms/pakx_admin_app/tasks.py
> +    courses = ', '.join(course_keys)
`courses` -> `courses_keys`

2021-06-28 20:56 UTC, mubtadaali commented on openedx/features/pakx/lms/pakx_admin_app/tasks.py
> +            recipient=Recipient(user.username, user.email),
since this will be a celery task, it will only receive JSON serializable params, not objects.

2021-06-28 20:56 UTC, mubtadaali commented on openedx/features/pakx/lms/pakx_admin_app/tasks.py
> +                                            CourseKey.from_string(course_key))
can be done in single line

2021-06-28 20:56 UTC, mubtadaali commented on openedx/features/pakx/lms/pakx_admin_app/utils.py
> +def get_accessible_users(user):
`get_org_users_qs`

2021-06-28 20:56 UTC, mubtadaali commented on openedx/features/pakx/lms/pakx_admin_app/views.py
> +        if request.data.get("ids") and request.data.get("course_keys"):
can we add check here if users_ids does not belong to same organization then it should raise error

2021-06-28 20:56 UTC, mubtadaali commented on openedx/features/pakx/lms/pakx_admin_app/views.py
> +class CourseEnrolmentViewSet(viewsets.ModelViewSet):
please add authentication & permission classes

2021-06-30 11:05 UTC, mubtadaali commented on openedx/features/pakx/lms/pakx_admin_app/tasks.py
> +                for course_key in course_keys:
can we make a query for all courses and then iterate over it instead of making a query in the loop

2021-07-01 04:15 UTC, mubtadaali approved these changes
just one observation

2021-07-01 04:15 UTC, mubtadaali commented on openedx/features/pakx/lms/pakx_admin_app/views.py
> +        user_qs = get_org_users_qs(request.user).values_list('id', flat=True).filter(id__in=request.data["user_ids"])
kindly resolve this

2021-07-01 12:21 UTC, emzubair approved these changes
👍🏽

2021-07-01 12:23 UTC, merged